version: 2
jobs:
  test:
    docker:
      - image: optechlab/indy-golang:1.15.0
      - image: optechlab/indy-pool:1.12.1

    working_directory: /go/src/github.com/findy-network/findy-agent

    environment:
      TEST_WORKDIR: /home/circleci/.test/

    steps:
      - checkout

      - run: make deps
      - run: make check
      - run: make test

workflows:
  version: 2
  test:
    jobs:
      - test
