pool-name: "FINDY_FILE_LEDGER"
steward-wallet-name: "sovrin_steward_wallet"
steward-wallet-key: "9C5qFG3grXfU9LodHdMop7CNVb3HtKddjgRc7oK5KhWY"
steward-did: "Th7MpTaRZVRYnPiabds81Y"
steward-seed: "000000000000000000000000Steward1"
host-port: 8090
server-port: 8090
grpc-port: 50051
grpc-cert-path: "./grpc/cert"
grpc-jwt-secret: "my-secret"
