name: release
on:
  push:
    tags:
      - "*"
jobs:
  e2e:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: test
        run: echo "implement e2e/acceptance tests"

  push-image:
    needs: e2e
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: all

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - run: echo "version=$(cat ./VERSION)" >> $GITHUB_ENV

      - uses: docker/build-push-action@v4
        with:
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/findy-agent:${{ env.version }}
            ghcr.io/${{ github.repository_owner }}/findy-agent:latest
          cache-from: type=registry,ref=ghcr.io/${{ github.repository_owner }}/findy-agent:latest
          cache-to: type=inline
          file: ./scripts/deploy/Dockerfile

  merge:
    needs: push-image
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          ref: master
      - name: merge
        run: |
          git fetch --tags origin
          git merge $GITHUB_REF
          git push origin master

  trigger:
    needs: merge
    runs-on: ubuntu-latest
    steps:
      - name: trigger aath build
        run: |
          curl \
            -X POST \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: Bearer $PAT" \
            -H "Content-Type: application/json" \
            https://api.github.com/repos/findy-network/findy-agent-backchannel/dispatches \
            -d '{"event_type":"bundle"}'
        env:
          PAT: ${{ secrets.FabTriggerToken }}
