name: test
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    container: ghcr.io/findy-network/findy-base:indy-1.16.ubuntu-18.04
    steps:
      - name: setup
        uses: actions/setup-go@v2
        with:
          go-version: 1.16.x
      - name: checkout
        uses: actions/checkout@v2
      - name: test
        run: make test
        env:
          TEST_WORKDIR: /github/home/.test/
          CI: true
      - name: scan
        run: make scan

